Now the jail base image is only built once.

diff --git a/docker-mkjail b/docker-mkjail
--- a/docker-mkjail
+++ b/docker-mkjail
@@ -14,7 +14,7 @@
 #
 
 if [ $# -lt 1 ]; then
-    echo "Usage: $0 USER [IMAGE] [HOSTNAME] [SHELL]" >&2
+    echo "Usage: $0 USER [HOSTNAME] [BASENAME] [IMAGE] [SHELL]" >&2
     exit 1
 fi
 
@@ -26,20 +26,32 @@ if [ "$REAPER" = "" ]; then
     exit 2
 fi
 
-JIMAGE=ubuntu:trusty
-JHOST=jail
-JSHELL=/bin/bash
+# The name of the jail container to use as a base
+JAIL_BASENAME=jail
+
+# The image to use when building the initial jail container
+JAIL_IMAGE=ubuntu:trusty
+
+# The hostname to use for the jail
+JAIL_HOSTNAME=jail
+
+# The shell to assign to the jailed user, within the jail
+JAIL_SHELL=/bin/bash
 
 if [ $# -ge 2 ]; then
-    JIMAGE="$2"
+    JAIL_HOSTNAME="$2"
 fi
 
 if [ $# -ge 3 ]; then
-    JHOSTNAME="$3"
+    JAIL_IMAGE="$3"
 fi
 
 if [ $# -ge 4 ]; then
-    JSHELL="$4"
+    JAIL_BASENAME="$4"
+fi
+
+if [ $# -ge 5 ]; then
+    JAIL_SHELL="$5"
 fi
 
 usr="$1"
@@ -61,25 +73,39 @@ if [ "$dir" = "/" ]; then
     exit 4
 fi
 
-sudo docker run --name="jail_${usr}" -h "$JHOST" -v "$dir:$dir:rw" -v "$REAPER:/sbin/reaper:ro" -d "$JIMAGE" /sbin/reaper
+docker inspect "$JAIL_BASENAME" >/dev/null 2>&1
 
 if [ $? -ne 0 ]; then
-    echo "Docker failed to create jail. If it already exists, and you want to recreate it, run:" >&2
-    echo >&2
-    echo "   docker stop jail_${usr}; docker rm jail_${usr}" >&2
-    echo >&2
-    echo "Then you can try to run this again." >&2
+    echo "Could not find jail container, creating..." >&2
+    sudo docker run --name="$JAIL_BASENAME" -h "$JAIL_HOSTNAME" -v "$REAPER:/sbin/reaper:ro" -d "$JAIL_IMAGE" /sbin/reaper
+    sudo docker-cmd "$JAIL_BASENAME" root apt-get -y update
+    sudo docker-cmd "$JAIL_BASENAME" root apt-get -y upgrade
+    sudo docker-cmd "$JAIL_BASENAME" root apt-get -y dist-update
+    sudo docker-cmd "$JAIL_BASENAME" root apt-get -y install python python-doc man-db manpages manpages-dev tmux
+    sudo docker-cmd "$JAIL_BASENAME" root apt-get -y install python-examples binutils binfmt-support cpp
+    sudo docker-cmd "$JAIL_BASENAME" root apt-get -y install tmux ctags vim vim-doc vim-scripts vim-nox
+    sudo docker-cmd "$JAIL_BASENAME" root sh -c "find / -type f '(' -perm -4000 -o -perm -2000 ')' -exec chmod ug-s {} \\; 2>/dev/null"
+    sudo docker stop "$JAIL_BASENAME"
+    sudo docker commit "$JAIL_BASENAME" "$JAIL_BASENAME"
+fi
+
+docker inspect "${JAIL_BASENAME}_$usr" >/dev/null 2>&1
+
+if [ $? -eq 0 ]; then
+    echo "Jail for user already exists, removing..." >&2
+    sudo docker stop "${JAIL_BASENAME}_$usr" >/dev/null 2>&1
+    sudo docker rm "${JAIL_BASENAME}_$usr" >/dev/null 2>&1
+fi
+
+echo "Creating jail for user $usr..." >&2
+docker run --name="${JAIL_BASENAME}_${usr}" -h "$JAIL_HOSTNAME" -v "$REAPER:/sbin/reaper:ro" -v "$dir:$dir:rw" -d "$JAIL_BASENAME"
+
+if [ $? -ne 0 ]; then
+    echo "Docker failed to create jail. :(" >&2
     exit 5
 fi
 
-sudo docker-cmd "jail_${usr}" root groupadd -g "$gid" "$grp"
-sudo docker-cmd "jail_${usr}" root useradd -s "$JSHELL" -u "$uid" -g "$gid" -d "$dir" "$usr"
-sudo docker-cmd "jail_${usr}" root apt-get -y update
-sudo docker-cmd "jail_${usr}" root apt-get -y upgrade
-sudo docker-cmd "jail_${usr}" root apt-get -y dist-update
-sudo docker-cmd "jail_${usr}" root apt-get -y install python python-doc man-db manpages manpages-dev tmux
-sudo docker-cmd "jail_${usr}" root apt-get -y install python-examples binutils binfmt-support cpp
-sudo docker-cmd "jail_${usr}" root apt-get -y install tmux ctags vim vim-doc vim-scripts vim-nox
-sudo docker-cmd "jail_${usr}" root sh -c "find / -type f '(' -perm -4000 -o -perm -2000 ')' -exec chmod ug-s {} \\; 2>/dev/null"
+sudo docker-cmd "${JAIL_BASENAME}_${usr}" root groupadd -g "$gid" "$grp"
+sudo docker-cmd "${JAIL_BASENAME}_${usr}" root useradd -s "$JAIL_SHELL" -u "$uid" -g "$gid" -d "$dir" "$usr"
 
 exit 0
